name: CI

# CI build triggered when a new version is pushed
on: push

# Defining a single job to "build"
jobs:

  build:

    # Specify the OS to run tests on
    runs-on: ubuntu-latest

    # A job is a sequence of steps
    steps:
    
    # Checkout the repository and set up Python
    # 'name' is an optional label shown in the log
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt .
      
      - name: Test with PyTest
        run: |
          python -m pytest --cov=inflammation.models tests/test_models.py